<link href="/assets/css/pages/error.css" rel="stylesheet" type="text/css"/>
<!-- BEGIN PAGE CONTENT-->          
 <div class="row">
    <div class="col-md-12 page-404">
       <div class="number">
          Ops!
       </div>

       <div class="erro">
           <h4>A página requisitada não pode ser exibida. Usuário sem permissão de acesso.</h4>
       </div>       
    </div>
 </div>
 <!-- END PAGE CONTENT-->