<?php $this->headTitle('Animais'); ?>

<ion-header-bar align-title="center" class="bar-balanced">
    <div class="buttons">
      <a class="button btn-back" href="/">Voltar</a>
    </div>    
    <h1 class="title">Animais</h1>
</ion-header-bar>
<ion-view>
    <ion-content class="has-header" scroll="true" padding="true">
        <div class="list">
            <?php foreach ($this->animais as $animal): ?>
            <a class="item item-text-wrap item-icon-right" href="<?php echo $this->url('lista', array(
            'controller' => 'animal',
            'nome' => $this->cleanURI($animal->getNome()),
            'id' => $animal->getId(),
        )); ?>">
                <?php echo $animal->getNome(); ?>
                <i class="icon ion-ios-arrow-right"></i>
            </a>
            <?php endforeach; ?>
        </div>
    </ion-content>
</ion-view>