<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Login</title>
        <!-- Bootstrap core CSS -->
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet" >

        <!-- JavaScript -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
        <!-- Custom styles for this template -->
        <style>
            body {
                background: #eee !important;	
            }

            .wrapper {	
                margin-top: 80px;
                margin-bottom: 80px;
            }

            form {
                max-width: 380px;
                padding: 15px 35px 45px;
                margin: 0 auto;
                background-color: #fff;
                border: 1px solid rgba(0,0,0,0.1);  

                .form-control {
                    position: relative;
                    font-size: 16px;
                    height: auto;
                    padding: 10px;

                }

                input[type="text"] {
                    margin-bottom: 10px;
                    border-bottom-left-radius: 0;
                    border-bottom-right-radius: 0;
                }

                input[type="password"] {
                    margin-bottom: 20px;
                    border-top-left-radius: 0;
                    border-top-right-radius: 0;
                }
            }

        </style>
    </head>
    <body>
        <div class="wrapper">
            <?php echo $this->form()->openTag($this->form); ?>    
            <?php echo $this->displayMessage(); ?>
            <h2 class="form-signin-heading">Login</h2>
            <?php echo $this->formText($this->form->get('login')); ?>
            <br />
            <?php echo $this->formPassword($this->form->get('senha')); ?>
            <hr />
            <?php echo $this->formSubmit($form->get('confirmar')); ?>  
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </body>
</html>