<?php echo $this->displayMessage(); ?>
<div class="panel panel-primary">
	<div class="panel-heading">Usuários</div>
	<div class="panel-body">
		<table class="table table-responsive table-bordered" id="data-table">
			<thead>
				<tr>
					<th>Nome</th>
					<th>Login</th>
					<th>E-mail</th>
					<th>Ativo</th>
					<th style="min-width: auto;"><a href="inserir" class="btn btn-sm btn-success"><i class="fa fa-plus"></i> Inserir</a></th>
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td><input type="text" class="form-control input-sm" placeholder="Pesquisar por nome" /></td>
					<td><input type="text" class="form-control input-sm" placeholder="Pesquisar por login" /></td>
					<td><input type="text" class="form-control input-sm" placeholder="Pesquisar por email" /></td>
					<td>
					   <select class="form-control input-sm" style="width: 180px;">
    					  <option></option>
    					  <option value="1">Ativos</option>
    					  <option value="0">Inativos</option>
					   </select>
					</td>
					<td>&nbsp;</td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>

<script type="text/javascript" src="/assets/scripts/pages/autenticacao/usuario.js"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	Usuario.init();
});
</script>