<!-- Sidebar -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Zoo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav side-nav">
            <li><a href="/cadastro/"><i class="fa fa-dashboard"></i> Dashboard</a></li>    
            <li><a href="/cadastro/animal/"><i class="fa fa-paw"></i> Animais</a></li>    
            <li><a href="/cadastro/ambiente/"><i class="fa fa-globe"></i> Ambientes</a></li>    
            <li><a href="/cadastro/alimentacao/"><i class="fa fa-leaf"></i> Alimentação</a></li>    
            <li><a href="/cadastro/recinto/"><i class="fa fa-university"></i> Recintos</a></li>    
            <li><a href="/cadastro/atividade/"><i class="fa fa-sun-o"></i> Atividades</a></li>    
            <?php //echo $this->menuCreator(); ?>
        </ul>
        <ul class="nav navbar-nav navbar-right navbar-user">
            <li class="dropdown user-dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> User <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li class="divider"></li>
                    <li><a href="/login/logout/"><i class="fa fa-power-off"></i> Sair</a></li>
                </ul>
            </li>
        </ul>
    </div><!-- /.navbar-collapse -->
</nav>