<?php echo $this->displayMessage(); ?>
<div class="panel panel-primary">
	<div class="panel-heading">Perfis</div>
	<div class="panel-body">
		<table class="table table-responsive table-bordered" id="data-table">
			<thead>
				<tr>
					<th>Nome</th>
					<th style="min-width: auto;">
					   <?php echo $this->linkInserir('acl', array('controller' => 'perfil', 'action' => 'inserir')); ?>
					</th>					
				</tr>
			</thead>
			<tfoot>
				<tr>
					<td><input type="text" class="form-control" /></td>
					<td>&nbsp;</td>
				</tr>
			</tfoot>
		</table>
	</div>
</div>

<script type="text/javascript" src="/assets/scripts/pages/acl/perfil.js"></script>
<script type="text/javascript">
jQuery(document).ready(function() {
	Perfil.init();
});
</script>