<?php $this->headTitle('Recintos'); ?>

<ion-header-bar align-title="center" class="bar-balanced">
    <h1 class="title">Recintos</h1>
</ion-header-bar>
<ion-view>
    <ion-content class="has-header" scroll="true" padding="true">
        <div class="list">
            <?php foreach ($this->recintos as $recinto): ?>
            <a class="item item-text-wrap item-icon-right" href="<?php echo $this->url('lista', array(
            'controller' => 'recinto',
            'nome' => $this->cleanURI($recinto->getNome()),
            'id' => $recinto->getId(),
        )); ?>">
                <?php echo $recinto->getNome(); ?>
                <i class="icon ion-ios-arrow-right"></i>
            </a>
            <?php endforeach; ?>
        </div>
    </ion-content>
</ion-view>